import { RESOURCES } from "../data/resources";

export const INIT_BOARD = [
   // Phobos Space Haven
   {
      x: 0,
      y: 0,
      available: false,
      name: 'PHOBOS SPACE HAVEN',
      oceanOnly: false,
      object: null,
      bonus: [],
   },
   // Ganymede Colony
   {
      x: 0,
      y: 0,
      available: false,
      name: 'GANYMEDE COLONY',
      oceanOnly: false,
      object: null,
      bonus: [],
   },
   // Tharsis
   {
      x: 0,
      y: 4,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.STEEL, RESOURCES.STEEL],
   },
   {
      x: 0,
      y: 6,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.STEEL, RESOURCES.STEEL],
   },
   { x: 0, y: 8, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 0,
      y: 10,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.CARD],
   },
   { x: 0, y: 12, available: false, name: null, oceanOnly: true, object: null, bonus: [] },
   { x: 1, y: 3, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 1,
      y: 5,
      available: false,
      name: 'THARSIS THOLUS',
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.STEEL],
   },
   { x: 1, y: 7, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 1, y: 9, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 1, y: 11, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 1,
      y: 13,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.CARD, RESOURCES.CARD],
   },
   {
      x: 2,
      y: 2,
      available: false,
      name: 'ASCRAEUS MONS',
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.CARD],
   },
   { x: 2, y: 4, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 2, y: 6, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 2, y: 8, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 2, y: 10, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 2, y: 12, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 2,
      y: 14,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.STEEL],
   },
   {
      x: 3,
      y: 1,
      available: false,
      name: 'PAVONIS MONS',
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.TITAN],
   },
   {
      x: 3,
      y: 3,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 3,
      y: 5,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 3,
      y: 7,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 3,
      y: 9,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 3,
      y: 11,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 3,
      y: 13,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 3,
      y: 15,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 0,
      available: false,
      name: 'ARSIA MONS',
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 2,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 4,
      available: false,
      name: 'NOCTIC CITY',
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 6,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 8,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 10,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 12,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 14,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 4,
      y: 16,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 1,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 3,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT, RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 5,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 7,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 9,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 11,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 13,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   {
      x: 5,
      y: 15,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   { x: 6, y: 2, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 6, y: 4, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 6, y: 6, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 6, y: 8, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 6, y: 10, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 6,
      y: 12,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.PLANT],
   },
   { x: 6, y: 14, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 7,
      y: 3,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.STEEL, RESOURCES.STEEL],
   },
   { x: 7, y: 5, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 7,
      y: 7,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.CARD],
   },
   {
      x: 7,
      y: 9,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.CARD],
   },
   { x: 7, y: 11, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 7,
      y: 13,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.TITAN],
   },
   {
      x: 8,
      y: 4,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.STEEL],
   },
   {
      x: 8,
      y: 6,
      available: false,
      name: null,
      oceanOnly: false,
      object: null,
      bonus: [RESOURCES.STEEL, RESOURCES.STEEL],
   },
   { x: 8, y: 8, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   { x: 8, y: 10, available: false, name: null, oceanOnly: false, object: null, bonus: [] },
   {
      x: 8,
      y: 12,
      available: false,
      name: null,
      oceanOnly: true,
      object: null,
      bonus: [RESOURCES.TITAN, RESOURCES.TITAN],
   },
]